#!/usr/bin/ksh

DIR_PATH=`dirname $0`
. $DIR_PATH/../globals

hmc_ip=`lsrsrc -d -x -s 'ManagerType = "HMC"' IBM.ManagementServer Hostname | head -n 1 | sed 's/[:"]//g'`

[ "x$hmc_ip" == "x" ] && {
        echo "Unable to detemine the HMC. Please maually fill this information from the GEP Frames Doc."
        exit $erro
}

hmc_host=`grep $hmc_ip $DIR_PATH/../misc/hmc.list | cut -f 1 -d :`

[ "x$hmc_host" == "x" ] && {
        echo "Unable to find the hostname for $hmc_ip"
        exit $erro
} || {
        echo $hmc_host
}
exit $info

