#!/usr/bin/ksh

DIR_PATH=`dirname $0`
. $DIR_PATH/../globals

host=`hostname | sed 's/\n//'`

hacmp_ver=`lslpp -cl cluster.es.server.rte 2>&1 | egrep "APPL|COMM" | awk -F : '{print $2" "$3}' | sort -u`

[ "x$hacmp_ver" == "x" ] || {
	rg_info=`/usr/es/sbin/cluster/utilities/clRGinfo`
	
	other_node_name=`/usr/es/sbin/cluster/utilities/cllsnode | grep -i NODE | grep -v $host | cut -d ' ' -f 2 | sed 's/://'`

	[ "x`/usr/es/sbin/cluster/utilities/clRGinfo | grep $host | grep ONLINE`" == "x" ] && { 
		my_node=Standby
	} || {
		my_node=Active
	}

	[ "x`/usr/es/sbin/cluster/utilities/clRGinfo | grep -v $host | grep ONLINE`" == "x" ] && { 
		other_node=Standby
	} || {
		other_node=Active
	}
	
	echo "Version : $hacmp_ver" 
	echo "This node is: $my_node"
	echo "Other node is: $other_node"
	echo "Other node name: $other_node_name" 
	exit $pass
} && {
	exit $fail
}  
