#!/usr/bin/ksh
# This will need some rethingking. If the MC levels 
# are changing for each machine type, then we will
# need to maintain a list of valid highest MC levels
# for each machine type.
#
# This script considers a single list of valid MCs

DIR_PATH=`dirname $0`
. $DIR_PATH/../globals

exit $fail

known_latest_mc="192102 271315"

need_update=0
for fcs in `lsmcode -A | grep fcs`
do
	this_one_needs=1
	for mc in $known_latest_mc
	do
		[ x`echo $fcs | grep $mc` == "x" ] || {
			this_one_needs=0
			break
		} 
	done
	[ $this_one_needs == 1 ] && {
		need_update=1
		out="$out,$fcs"
	}
done
echo $out 
[ $need_update == 1 ] && exit $pass
exit $fail
